### ISSUE TITLE
ReadySet enters invalid state after Postgres WAL rotates

### ISSUE THREAD

**Issue by readyset-railway** [readysettech/readyset#238] opened 2023-08-10 13:48 UTC
### Summary

When ReadySet doesn't keep up with the replication throughput, Postgres rotates the WAL. ReadySet doesn't send the correct last commit WAL position to upstream even after it's caught up.

### Description

When a large number of transactions are done in the upstream database, the replication slot goes into `unreserved` status. Postgres runs checkpoints each 5 minutes. If the replication slot stays in the `unreserved` status,  Postgres will invalidate that slot and mark it as `lost`. This would cause ReadySet to crash and go into an infinite loop.

If you run a simple `INSERT` sql query after 10 seconds (`STATUS_UPDATE_INTERVAL`), the WAL status would change back to `reserved`.

```
INSERT INTO sbtest1 VALUES(10001,1,'c','d');
```

### Expected behavior

ReadySet should send the correct last commit LSN to upstream and the replication slot status should change back to "`reserved`".

### Actual behavior

The last commit LSN sent by ReadySet is incorrect and the replication slot stays in `unreserved` status. It changes to `lost` upon a checkpoint or a restart.

### Steps to reproduce 

1. Change the `max_slot_wal_keep_size` to 1 in Postgres config(`/usr/local/var/postgresql@15/postgresql.conf` in OSX) and restart the Postgres service.
2. Create a database and prepare it using `sysbench`.

   ```
   sysbench --pgsql-user=sandaru1 --pgsql-password=readyset --pgsql-db=pgbench --pgsql-port=5432 --pgsql-host=127.0.0.1 --db-driver=pgsql --tables=5 --threads=50 oltp_read_write prepare
   ```
3. Run ReadySet with created database as the upstream.
4. Check the replication slot WAL status by running the following SQL query in psql. The status should be "`reserved`".

   ```
   SELECT slot_name, wal_status FROM pg_replication_slots;
   ```
5. Run `sysbench` to do a high number of transactions against ReadySet.

   ```
   sysbench --time=5 --pgsql-user=sandaru1 --pgsql-password=readyset --pgsql-db=pgbench --pgsql-port=5433 --pgsql-host=127.0.0.1 --db-driver=pgsql --tables=5 --threads=50 oltp_read_write run
   ```
6. Check the WAL status of the replication as shown in step 4. If it's not changed to `unreserved`, go back to step 5.
7. Wait 5 minutes until the Postgres checkpoint runs or restart the Postgres server.
8. The replication status would change to `lost`. ReadySet will disconnect and go into an infinite loop.

### ReadySet version

e32cc598a01e67b6ce823d8fd14423ae740a6b9a

### Upstream DB type and version

Postgres 15.3

### Logs

ReadySet logs

```
2023-08-10T13:26:40.295303Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-08-10T13:26:40.296421Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-08-10T13:26:40.323345Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-08-10T13:26:40.326990Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-08-10T13:26:40.338684Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: db error: ERROR: cannot read from logical replication slot "readyset"
DETAIL: This slot has been invalidated because it exceeded the maximum reserved size.
2023-08-10T13:26:40.338709Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: db error: ERROR: cannot read from logical replication slot "readyset"
DETAIL: This slot has been invalidated because it exceeded the maximum reserved size. timeout_sec=1
2023-08-10T13:26:41.356188Z  INFO replicators::postgres_connector::ddl_replication: Setting up DDL replication
2023-08-10T13:26:41.356929Z  INFO tokio_postgres::connection: NOTICE: schema "readyset" already exists, skipping
2023-08-10T13:26:41.363518Z  INFO replicators::postgres_connector::ddl_replication: Set up DDL replication
2023-08-10T13:26:41.367929Z  INFO replicators::noria_adapter: Connected to PostgreSQL
2023-08-10T13:26:41.370210Z  WARN replicators::noria_adapter: Restarting adapter after error encountered error=Error during replication: db error: ERROR: cannot read from logical replication slot "readyset"
DETAIL: This slot has been invalidated because it exceeded the maximum reserved size.
2023-08-10T13:26:41.370236Z ERROR replicators: Error in replication, will retry after timeout error=Error during replication: db error: ERROR: cannot read from logical replication slot "readyset"
DETAIL: This slot has been invalidated because it exceeded the maximum reserved size. timeout_sec=1
```

Postgres logs

```
2023-08-10 18:56:39.479 +0530 [2775] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-08-10 18:56:39.516 +0530 [2775] LOG:  invalidating slot "readyset" because its restart_lsn 8/A50DC178 exceeds max_slot_wal_keep_size
2023-08-10 18:56:39.539 +0530 [2775] LOG:  checkpoint complete: wrote 1816 buffers (11.1%); 0 WAL file(s) added, 1 removed, 0 recycled; write=0.024 s, sync=0.011 s, total=0.061 s; sync files=45, longest=0.002 s, average=0.001 s; distance=13080 kB, estimate=13080 kB
2023-08-10 18:56:39.545 +0530 [2770] LOG:  database system is ready to accept connections
2023-08-10 18:56:40.338 +0530 [2794] ERROR:  cannot read from logical replication slot "readyset"
2023-08-10 18:56:40.338 +0530 [2794] DETAIL:  This slot has been invalidated because it exceeded the maximum reserved size.
2023-08-10 18:56:40.338 +0530 [2794] STATEMENT:  START_REPLICATION SLOT readyset LOGICAL 8/A6085AB8 (
"proto_version" '1',
"publication_names" 'readyset'
, "messages" 'true'
)
2023-08-10 18:56:41.370 +0530 [2797] ERROR:  cannot read from logical replication slot "readyset"
2023-08-10 18:56:41.370 +0530 [2797] DETAIL:  This slot has been invalidated because it exceeded the maximum reserved size.
2023-08-10 18:56:41.370 +0530 [2797] STATEMENT:  START_REPLICATION SLOT readyset LOGICAL 8/A6085AB8 (
"proto_version" '1',
"publication_names" 'readyset'
, "messages" 'true'
)
```

**Comment by ethan-readyset** [comment] 2023-09-21 22:58
There was a small bug in the fix for [REA-3303](https://linear.app/readyset/issue/REA-3303/readyset-repeatedly-tries-to-connect-to-an-invalidated-replication) that was fixed [here](https://gerrit.readyset.name/c/readyset/+/6094), but otherwise, this appears to be a duplicate of that ticket. I can't reproduce the issue anymore (we always correctly report our position and our slot goes back to `reserved`, so I think we can call this done

**Closed** 2023-09-21 22:58 UTC
Labels: bug, High priority, 4 points
