### ISSUE TITLE
ReadySet attempts encoding PassThrough as Text

### ISSUE THREAD

**Issue by dfwilbanks395** [readysettech/readyset#268] opened 2023-08-11 22:09 UTC
DBeaver will cause ReadySet to attempt to encode PassThrough data as Text, which is unsupported (see attached statement log). It appears that this can be triggered by issuing a query via the execute protocol with either no result format or a text result format specified for columns that contain unsupported types.

Our PassThrough datatype is only implemented for the binary format, but we could implement that type for the text format.

[laravel-pg_statements.log](https://uploads.linear.app/76d4be3b-10f5-452e-a0bd-5ce299bfcdf4/a943a053-37dc-4bf5-b0d2-a2c1fe8da0cd/f07aebe3-a4e8-4dab-b86b-42830745e565)

**Comment by dfwilbanks395** [comment] 2023-08-11 22:09
@glittershark this might be something we consider critical for this quarter since it prevents proxying. Not doing this would block some unknown subset of customers.

Also worth considering whether to implement prep/exec passthrough the same way we implement simple query passthrough.

**Comment by nickelization** [comment] 2023-08-17 14:42
This is basically a duplicate of [REA-1645](https://linear.app/readyset/issue/REA-1645/postgresql-support-text-transfer-mode-for-passthrough-types), but I'll close that one instead even though it's older, since this seems to be the one that we're using for planning purposes.

**Comment by nickelization** [comment] 2023-08-18 20:02
This is definitely trickier than I'd anticipated. The `tokio-postgres` library is hard-coded to request the binary response format when it sends a `BIND`, so at a minimum we definitely need to modify that to enable requesting text format (so that we can then pass the text-formatted result back to the client connected to ReadySet). But once that's done there a few different ways that we could proceed:

* We pass through the same result formats upstream that the client requested, so the proxied query returns results in the same format the client requested. The trouble here is that we decode all the results from the upstream query using the `FromSql` implementation on `PsqlValue`, and that's only implemented for the binary format, not the text format. Further, the trait is built in a way that doesn't even specify the result format to the function that does the decoding, because it's built off of the assumption that everything is hardcoded to use binary format. Since implementing `FromSql` is mandatory for decoding query results, we'd need to do some pretty significant hacking to make this work. The one exception here is in the Passthrough case, since we don't care about result format, since we just pass the data back to the client as-is. That brings us to option #2:
* We only request text format for a column if the client requested it in text format *and* it's an unsupported type. The problem here is that we don't *know* the result types until we get back the response to the `DESCRIBE` request that we send after the `BIND`. We could start over and send a new `BIND` based off the results of the `DESCRIBE`, but this would add an extra round trip to every proxied query (and be complex to implement as well) so this is probably a non-starter. (We could try to ameliorate this with some kind of caching solution for query result types, but this gets complicated quick, since we need to keep track of everything and also invalidate cache entries when tables are altered, so this is probably not worth the headache.)
* On the other hand, we could forward all of the client's result formats to the upstream query, and also just use passthrough for *everything*. Then we don't need to worry about the result format, because we don't actually decode anything. However, every passthrough value we use requires a `Box` so this could get expensive. Maybe we could do some kind of clever thing where we have two different Passthrough variants, and one of them is automatically used for small values and stores the raw data directly in the variant instead of allocating a `Box` for it. But ultimately this solution is close enough to just passing back entire raw result packets and sending them back to the client, that we probably might as well just do that the way we do for `SimpleQuery`.

So all that said, I think @dfwilbanks395's suggestion of just doing the same thing for the `PARSE`/`BIND`/`DESCRIBE`/`EXECUTE` path that we do for the simple query path is probably the right way to go, but this is probably also trickier to implement than in the simple query case. On the bright side, I imagine it might net us some performance boosts for proxied queries though, as an added bonus on top of fixing this bug.

**Closed** 2023-08-26 20:31 UTC
Labels: bug, High priority
