### ISSUE TITLE
Discourse db migration failure

### ISSUE THREAD

**Issue by readyset-railway** [readysettech/readyset#562] opened 2023-09-07 17:48 UTC
### Description

When the Discourse is configured to connect to ReadySet, the database migration fails.

### Expected behavior

The db migration. should run without any issues. This works when it's directly connected to Postgres.

### Actual behavior

Fails in `AddIconToExpressionTypes` migration. See the logs.

### Steps to reproduce 

Follow the steps here : [https://github.com/discourse/discourse/blob/main/docs/DEVELOPER-ADVANCED.md](https://github.com/discourse/discourse/blob/main/docs/DEVELOPER-ADVANCED.md)

The database can be configured in `config/database.yml`.

```
development:
  prepared_statements: false
  adapter: postgresql
  database: discourse
  host: 127.0.0.1
  port: 5450
  username: sandaru1
  password: readyset
```

The installation fails at `bundle exec rake db:migrate`

### ReadySet version

0f6c3ba4a3f0d06e1307da9281c6a2cc862881e9

### Upstream DB type and version

PostgreSQL 15.3

### Logs

```
== 20120802151210 AddIconToExpressionTypes: migrating =========================
-- add_column(:expression_types, :icon, :string, {:limit=>20})
   -> 0.0006s
-- execute("UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::ObjectNotInPrerequisiteState: ERROR:  cannot update table "expression_types" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
/Users/sandaru1/Sites/readyset/discourse/db/migrate/20120802151210_add_icon_to_expression_types.rb:7:in `change'
/Users/sandaru1/Sites/readyset/discourse/lib/freedom_patches/schema_migration_details.rb:8:in `block in exec_migration'
/Users/sandaru1/Sites/readyset/discourse/lib/freedom_patches/schema_migration_details.rb:8:in `exec_migration'
/Users/sandaru1/Sites/readyset/discourse/lib/migration/safe_migrate.rb:28:in `migrate'
/Users/sandaru1/Sites/readyset/discourse/lib/migration/safe_migrate.rb:53:in `migrate'
/Users/sandaru1/Sites/readyset/discourse/lib/tasks/db.rake:246:in `block (2 levels) in <main>'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/tasks/db.rake:221:in `block in <main>'
/Users/sandaru1/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/Users/sandaru1/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: PG::ObjectNotInPrerequisiteState: ERROR:  cannot update table "expression_types" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
/Users/sandaru1/Sites/readyset/discourse/db/migrate/20120802151210_add_icon_to_expression_types.rb:7:in `change'
/Users/sandaru1/Sites/readyset/discourse/lib/freedom_patches/schema_migration_details.rb:8:in `block in exec_migration'
/Users/sandaru1/Sites/readyset/discourse/lib/freedom_patches/schema_migration_details.rb:8:in `exec_migration'
/Users/sandaru1/Sites/readyset/discourse/lib/migration/safe_migrate.rb:28:in `migrate'
/Users/sandaru1/Sites/readyset/discourse/lib/migration/safe_migrate.rb:53:in `migrate'
/Users/sandaru1/Sites/readyset/discourse/lib/tasks/db.rake:246:in `block (2 levels) in <main>'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:53:in `block in synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:49:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/distributed_mutex.rb:34:in `synchronize'
/Users/sandaru1/Sites/readyset/discourse/lib/tasks/db.rake:221:in `block in <main>'
/Users/sandaru1/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/Users/sandaru1/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
```

**Comment by lukoktonos** [comment] 2023-09-07 18:20
As a part of snapshotting, we do this for tables that don't have replica identity full, which is needed for tables that don't have a primary key

```
    async fn set_replica_identity_for_tables(
        &self,
        table_list: &[TableEntry],
    ) -> ReadySetResult<()> {
        let tables_needing_replica_identity = get_transaction!(self)
            .query(
                // Find all tables that are in the table list, and don't already have a primary key
                // or a non-default replica identity set
                "select n.nspname as schema, c.relname as name from pg_class c
                 join pg_namespace n
                 on n.oid = c.relnamespace
                 where c.oid not in (select indrelid from pg_index where indisprimary)
                 and c.relreplident = 'd'
                 and c.oid = any ($1::oid[])",
                &[&table_list.iter().map(|t| t.oid).collect::<Vec<_>>()],
            )
            .await?;

        for table_row in tables_needing_replica_identity {
            let schema: String = table_row.get("schema");
            let name: String = table_row.get("name");
            trace!(%schema, %name, "Setting REPLICA IDENTITY FULL for table");
            get_transaction!(self)
                .execute(
                    &format!(r#"ALTER TABLE "{schema}"."{name}" REPLICA IDENTITY FULL"#),
                    &[],
                )
                .await?;
        }

        Ok(())
    }
```

The migration is adding a column (ALTER TABLE) then updating the table to change columns where expression_index = 1 to the string 'heart'. It's failing on the update. 

```
class AddIconToExpressionTypes < ActiveRecord::Migration[4.2]
  def change
    add_column :expression_types, :icon, :string, limit: 20

    execute "UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1"
  end
end
```

According to @readyset-railway this update is the only one causing the db:migrate step to fail. This table is later dropped as a part of a subsequent migration: [https://github.com/discourse/discourse/blob/main/db/migrate/20120812235417_retire_expressions.rb](https://github.com/discourse/discourse/blob/main/db/migrate/20120812235417_retire_expressions.rb)

**Comment by lukoktonos** [comment] 2023-09-07 18:29
My guess is that this is a race between a create+alter+write and the readyset snapshot doing the `alter table replica identity full` where the replica full happens after the `update`

**Comment by lukoktonos** [comment] 2023-09-07 18:43
To summarize the problem:

1. Postgres doesn’t allow `updates` against tables that don’t have primary keys if replication is enabled--it wouldn’t know which row to update
2. Readyset sets `replica identity full` during snapshotting, which avoids the problem in (1), but only for tables that it sees during snapshotting
3. If a workflow creates tables after snapshotting and before we re-snapshot, the table could be the type that doesn’t have `replica identity full` or a primary key, so updates aren’t valid.
4. Rails tries to do updates to that table, not knowing that we have made a new restriction on that by enabling logical replication
5. Update fails, so rails migration fails.

**Comment by aglover** [comment] 2023-09-07 21:26
Would this be an issue if for a migration if users unconnected ReadySet ran the migration, and then re-snapshotted things?

**Comment by readyset-railway** [comment] 2023-09-07 22:13
If the DB is connected to RS at least once, it would create the replication slot in the DB. So, the migration would fail. Users have to run the migration before connecting to RS.

**Comment by lukoktonos** [comment] 2023-09-07 22:54
More details in [https://readyset-workspace.slack.com/archives/C05Q91BKEP4/p1694109687813049](https://readyset-workspace.slack.com/archives/C05Q91BKEP4/p1694109687813049), but my summary was actually incomplete--we also add `replica identity full` via a trigger in postgres after `create table` ddl is executed. I am not sure why that isn't sufficient in this case, but it appears the `update` is happening before that `replica identity full` has taken effect. It may be related to the `alter table` just before the update in some way.

**Comment by aglover** [comment] 2023-09-07 22:58
What is the solution if a migration has to happen after RS has been connected? That is, the database/application has changed due to a new feature? Would they need to turn off RS and remove a table/rows from some system table?

**Comment by readyset-railway** [comment] 2023-09-08 01:01
This is only happening for one specific table because there is no primary key on it. Any subsequent migrations with table changes would most likely work. If it doesn't, the replication slot has to be removed with the "`--cleanup`" parameter of ReadySet, then reconnect again.

**Comment by aglover** [comment] 2023-09-08 01:15
It'll be good if we can document this as it seems it may pop up in the near future for users.

**Comment by lukoktonos** [comment] 2023-09-08 18:08
```
2023-09-08 17:33:17.927 UTC [79] LOG:  statement: BEGIN
2023-09-08 17:33:17.928 UTC [79] LOG:  statement: ALTER TABLE "expression_types" ADD "icon" character varying(20)
2023-09-08 17:33:17.930 UTC [79] LOG:  statement: UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1
2023-09-08 17:33:17.930 UTC [79] ERROR:  cannot update table "expression_types" because it does not have a replica identity and publishes updates
2023-09-08 17:33:17.930 UTC [79] HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
2023-09-08 17:33:17.930 UTC [79] STATEMENT:  UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1
2023-09-08 17:33:17.931 UTC [79] LOG:  statement: ROLLBACK
```

Above is the sequence of events when db:migrate is run. I tried to reproduce it with a .sql script

```
BEGIN;
ALTER TABLE "expression_types" ADD "icon" character varying(20);
UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1;
COMMIT;
```

But it didn't reproduce:

```
2023-09-08 17:54:00.237 UTC [157] LOG:  statement: BEGIN
2023-09-08 17:54:00.237 UTC [157] LOG:  statement: ALTER TABLE "expression_types" ADD "icon" character varying(20);
2023-09-08 17:54:00.241 UTC [157] LOG:  statement: UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1;
2023-09-08 17:54:00.242 UTC [157] LOG:  statement: COMMIT
```

But if we do all the migrations that touch `expression_types`, this does reproduce:

```
BEGIN;
DROP TABLE IF EXISTS "expression_types";
COMMIT;

BEGIN;
CREATE TABLE "expression_types" ("id" serial NOT NULL PRIMARY KEY, "site_id" integer NOT NULL, "name" character varying(50) NOT NULL, "long_form" character varying(100) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE UNIQUE INDEX "index_expression_types_on_site_id_and_name" ON "expression_types" ("site_id", "name");
COMMIT;

BEGIN;
SELECT 'boolean'::regtype::oid;
ALTER TABLE "expression_types" ADD "flag" boolean DEFAULT FALSE;
COMMIT;

BEGIN;
ALTER TABLE "expression_types" ADD "description" text;
COMMIT;
BEGIN;

BEGIN;
ALTER TABLE "expression_types" ADD "expression_index" integer;
UPDATE expression_types SET expression_index = id;
ALTER TABLE "expression_types" DROP COLUMN "id";
CREATE UNIQUE INDEX "index_expression_types_on_site_id_and_expression_index" ON "expression_types" ("site_id", "expression_index");
COMMIT;

BEGIN;
ALTER TABLE "expression_types" ADD "icon" character varying(20);
UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1;
COMMIT;
```

```
ERROR:  cannot update table "expression_types" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
ROLLBACK
```

**Comment by glittershark** [comment] 2023-09-08 18:26
I'm betting that's happening because the 

```
ALTER TABLE "expression_types" ADD "flag" boolean DEFAULT FALSE;
```

performs an update to set `flag` on all rows to `false` after adding the column

**Comment by lukoktonos** [comment] 2023-09-08 18:27
shrunken minimal repro:

(the 3rd txn is needed and each step in it is needed

```
BEGIN;
DROP TABLE IF EXISTS "expression_types";
COMMIT;

BEGIN;
CREATE TABLE "expression_types" ("id" serial NOT NULL PRIMARY KEY, "site_id" integer NOT NULL, "name" character varying(50) NOT NULL, "long_form" character varying(100) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
CREATE UNIQUE INDEX "index_expression_types_on_site_id_and_name" ON "expression_types" ("site_id", "name");
COMMIT;

BEGIN;
ALTER TABLE "expression_types" ADD "expression_index" integer;
UPDATE expression_types SET expression_index = id;
ALTER TABLE "expression_types" DROP COLUMN "id";
CREATE UNIQUE INDEX "index_expression_types_on_site_id_and_expression_index" ON "expression_types" ("site_id", "expression_index");
COMMIT;

BEGIN;
ALTER TABLE "expression_types" ADD "icon" character varying(20);
UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1;
COMMIT;
```

**Comment by glittershark** [comment] 2023-09-08 18:29
oh, yeah, I mean… `drop column "id"`

there's your problem

**Comment by glittershark** [comment] 2023-09-08 18:29
there's kinda nothing we can do here tbh, this is well past the pareto frontier for ROI on trying to automatically set replica identities

**Comment by lukoktonos** [comment] 2023-09-08 18:42
yep this also repros--this is the "if a table starts with a primary key and then drop it, it won't work" case

```
DROP TABLE IF EXISTS "expression_types";
CREATE TABLE "expression_types" ("id" serial NOT NULL PRIMARY KEY, "site_id" integer NOT NULL, "name" character varying(50) NOT NULL, "long_form" character varying(100) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
ALTER TABLE "expression_types" ADD "expression_index" integer;
UPDATE expression_types SET expression_index = id;
ALTER TABLE "expression_types" DROP COLUMN "id";
ALTER TABLE "expression_types" ADD "icon" character varying(20);
UPDATE expression_types SET icon = 'heart' WHERE expression_index = 1;
```

As does:

```
ubuntu@ip-10-0-0-227 ~/discourse (main)> cat repro.sql
DROP TABLE IF EXISTS "expression_types";
CREATE TABLE "expression_types" ("id" serial NOT NULL PRIMARY KEY, "site_id" integer NOT NULL, "name" character varying(50) NOT NULL, "long_form" character varying(100) NOT NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL);
ALTER TABLE "expression_types" DROP COLUMN "id";
UPDATE expression_types SET site_id = 1;
```

**Comment by lukoktonos** [comment] 2023-09-08 18:44
Closing as this is the currently expected behavior if a user creates a table with a primary key and then drops it: [https://linear.app/readyset/issue/REA-1799#comment-0a1b49a6](https://linear.app/readyset/issue/REA-1799#comment-0a1b49a6) . We will be discussing whether it makes sense to back out setting `replica identity full` altogether separately.

**Closed by lukoktonos** 2023-09-08 18:44 UTC
Labels: bug
